### ISSUE TITLE
vs-adapter not doing anything

### ISSUE THREAD

**Issue by mcfly9** [MortenHoustonLudvigsen/KarmaTestAdapter#6]
Hey,

Installed and configured karma, able to launch directly using karma start configile.js. If I launch using --log-level debug, I see it is loading the vs reporter plugin. No output is generated however and no tests are discovered.
I also tiredto add a karma-vs-reporter.json to force logging but no log folder was created:

{
    "karmaConfigFile": "karma.conf.js",
    "ServerMode": true,
    "ServerPort": 3535,
    "LogToFile": true,
    "LogDirectory": "KarmaTestAdapter",
    "OutputDirectory": "KarmaTestAdapter/Output",
    "config": {
        "browsers": [
            "Chrome"
        ]
    }
}

What am I doing wroing?

Using VS2015.CTP5 btw.

**Comment by MortenHoustonLudvigsen** [comment]
You write that karma works when you run:

```
karma start configile.js
```

Is `configile.js` the name of your cofiguration file? If so, it will not be found by the adapter by default. However, you should be able to get it to work by specifying it in `karma-vs-reporter.json`:

```json
{
    "karmaConfigFile": "configile.js",
    "ServerMode": true,
    "ServerPort": 3535,
    "LogToFile": true,
    "LogDirectory": "KarmaTestAdapter",
    "OutputDirectory": "KarmaTestAdapter/Output",
    "config": {
        "browsers": [
            "Chrome"
        ]
    }
}
```

Does this help?

**Comment by mcfly9** [comment]
Hey Morten,
I figured out the issue meanwhile. Seems that paths get mixed up if I open the solution and not open just the files as a website. I managed to bring vs-reporter to life by opening from VS as a website.
Still experimenting with the proper path and include combinations.

Of course I used 'configfile.js' as an example. Here's my setup:

solution/webproject/karma.conf.js
`basePath: 'webproject',
files: ['Scripts/**/*.js'] // and a lot of others`

solution/webproject/karma-vs-reporter.json

`{ "karmaConfigFile": "webproject/karma.conf.js" }`

**Comment by MortenHoustonLudvigsen** [comment]
Great!

About paths. The paths in `karma-vs-reporter.json` should be relative to the directory in which `karma-vs-reporter.json` resides. So it should be:

```json
"karmaConfigFile": "karma.conf.js"
```

Or just omit `"karmaConfigFile"`, as you are using the default file name.

**Comment by MortenHoustonLudvigsen** [comment]
Btw. I have not tested the adapter using web sites - only web applications. Could this be the problem?
I will look into this when I have time.

**Comment by mcfly9** [comment]
It's actually a web application.

It seems I was able to manage the path problem. VS2015.CTP5 crashes on me however everytime after loading. A bunch of System.OutOfMemoryExceptions around various json assemblies. These don't show without vs_reporter.
I have also tried to move away all JS files to a different location (outside of the project) to see if it helps but not really, constantly crashing VS.

**Comment by MortenHoustonLudvigsen** [comment]
Hmm...

I am using VS2015.CTP5 in a project I am working on a the moment, and I don't have these issues. Would it be possible for you to send me a project with the problem to mlu@2ps.dk. Then I will see if I can reproduce the problem.

**Comment by mcfly9** [comment]
Sorry, lot of stuff in the project I can't share. Will try to build a new solution and add back the project items and see how it goes, ok?

**Comment by mcfly9** [comment]
But thanks for the super effort. Really looking forward to finding the issue.

**Comment by MortenHoustonLudvigsen** [comment]
Of course! You could also point me to a git repository.

**Comment by cResults** [comment]
Morten, 

I saw that you added "server mode" in response to my posts on Visual Studio Gallery.  With high anticipation, I reinstalled Karma Test Adapter to check out the improved performance and smoother experience.  However, after following all the steps in your video and adding karma-vs-reporter.json to the project, my tests did not show up at all in the VS Test Explorer.  Much like what mcfly9 describes at the beginning of this thread.

I tried following the same procedure on the same solution but on another machine installing everything from the beginning and experienced the same results; no tests.  

Then I created a new project and followed your video exactly.  This time the single test was displayed in Text Explorer, however, when I clicked Run All, the progress bar at the top of Test Explorer just continues to stream green across and the tests never finishes.  I had to cancel.

The promise of your adapter is higher than the others that I've been able to find, so if there is anything I can do to help you, please let me know.

Respectfully

cResults

**Comment by MortenHoustonLudvigsen** [comment]
If you could make a project with the problem and put it on GitHub that would really help!

**Comment by MortenHoustonLudvigsen** [comment]
I have just released a new version of the adapter. It should supply better information on errors. If an error occurs while reading `karma-vs-reporter.json` it will *not* be logged to a log file, but it will be shown in the output window in Visual Studio. I hope this helps tracking down the problems connected with this issue.

**Comment by MortenHoustonLudvigsen** [comment]
With the latest release (version 0.7.2) I have improved handling of errors. If there are errors in `karma-vs-reporter.json` no tests will be shown or run in the test explorer. Any error messages can be found in `%appdata%\2PS\KarmaTestAdapter\KarmaTestAdapter.log`.
Would it be possible to try with this new release, and report your experiences here? That would be very helpful!

**Comment by bfoo2222** [comment]
Hi Morten
I now have the tests showing in my test explorer, but I have the above where the test explorer just shows it as running, but nothing happens. With 0.7.3, I get this in the output window 

[karma] [Run] INFO [Test run]: Start
[karma] [Run] INFO [karma]: Karma v0.12.31 server started at http://localhost:62109/

But it will just wait. It has no errors in the log. But if I click on the url to open a browser then it will return the results and the test explorer will then update with the results. 

Hope that helps. :)

**Comment by MortenHoustonLudvigsen** [comment]
@bfoo2222 Could you start a new issue for this, please? :-)

**Comment by MortenHoustonLudvigsen** [comment]
@bfoo2222 Ah, that makes sense - remember that comments in GitHub are written in Markdown. You can write verbertim text by indenting 4 spaces or by fencing it thus:

    ```javascript
    files: [
        // App files
        "**/*Files.js",
        // Specs
        "**/*Specs.js"
    ]
    ```

I will try to reproduce the issue. In the mean time, could you telle me which version of Karma and Karma plugins you are using? Thanks. :-)

**Comment by MortenHoustonLudvigsen** [comment]
@bfoo2222  I have tried to recreate the problem without luck (it works for me). I have put my efforts in GitHub: <https://github.com/MortenHoustonLudvigsen/KarmaTestAdapter-Issue6>. Would it be possible for you to try that project, to see if you have the problem with this project?

**Comment by bfoo2222** [comment]
Hi Morten here are my dev dependencies of karma and its plugins.
   "karma": "^0.12.24",
    "karma-chrome-launcher": "^0.1.7",
    "karma-cli": "0.0.4",
    "karma-firefox-launcher": "^0.1.3",
    "karma-ie-launcher": "^0.1.5",
    "karma-jasmine": "^0.2.3",
    "karma-opera-launcher": "^0.1.0",
    "karma-safari-launcher": "^0.1.1",
    "karma-vs-reporter": "^0.7.0",
    "karma-xml-reporter": "^0.1.4"
I will try when I get a chance to pull your project and see if I have any problems. Thanks much appreciated.

**Comment by MortenHoustonLudvigsen** [comment]
@bfoo2222 Thank you so much. I have just updated [KarmaTestAdapter-Issue6](https://github.com/MortenHoustonLudvigsen/KarmaTestAdapter-Issue6) with the versions you supplied. I can still successfully run tests in VS 2013 and VS 2015 CTP.

**Comment by MortenHoustonLudvigsen** [comment]
@bfoo2222 I have added you as a collaborator to [KarmaTestAdapter-Issue6](https://github.com/MortenHoustonLudvigsen/KarmaTestAdapter-Issue6), so you can make any changes you want to make the adapter fail! :smile:

**Comment by cResults** [comment]
Today I installed 0.7.3

First I checked the web app project I made following the steps in your video.  The test shows up in Test Explorer, but never runs or completes. I let it run and then canceled twice.  Here is the content of the log file:
```
[04.02.2015 15:23:58.686] KarmaTestContainerDiscoverer created
[04.02.2015 15:23:59.608] [Get config] Start (e:\projects\karmvsadapter\karmvsadapter\karma.conf.js)
[04.02.2015 15:23:59.712] [Get config] node node_modules\karma-vs-reporter\karma-vs-reporter get-config -o C:\Users\David\AppData\Local\Temp\tmp69F1.tmp
[04.02.2015 15:24:00.869] [Get config] Finished (e:\projects\karmvsadapter\karmvsadapter\karma.conf.js)
[04.02.2015 15:24:00.900] Watching 'karmvsadapter\karma-vs-reporter.json'
[04.02.2015 15:24:00.902] Watching 'karmvsadapter\karma.conf.js'
[04.02.2015 15:24:00.906] Watching 'karmvsadapter\tests\**\*Test.js'
[04.02.2015 15:24:03.895] [Discover] Start (e:\projects\karmvsadapter\karmvsadapter\karma.conf.js)
[04.02.2015 15:24:03.938] [Discover] node node_modules\karma-vs-reporter\karma-vs-reporter discover -o C:\Users\David\AppData\Local\Temp\tmp7AA1.tmp
[04.02.2015 15:24:06.465] [Discover] Finished (e:\projects\karmvsadapter\karmvsadapter\karma.conf.js)
[04.02.2015 15:24:07.129] [Discover] Start (e:\projects\karmvsadapter\karmvsadapter\karma.conf.js)
[04.02.2015 15:24:07.172] [Discover] node node_modules\karma-vs-reporter\karma-vs-reporter discover -o C:\Users\David\AppData\Local\Temp\tmp8743.tmp
[04.02.2015 15:24:07.693] [Discover] Finished (e:\projects\karmvsadapter\karmvsadapter\karma.conf.js)
[04.02.2015 15:24:07.742] [Run] Start (e:\projects\karmvsadapter\karmvsadapter\karma.conf.js)
[04.02.2015 15:24:07.928] [Run] node node_modules\karma-vs-reporter\karma-vs-reporter run -p 60910 -o C:\Users\David\AppData\Local\Temp\tmp89A5.tmp -v C:\Users\David\AppData\Local\Temp\tmp89A6.tmp
[04.02.2015 15:24:12.746] [Run] INFO [Test run]: Start
[04.02.2015 15:24:12.764] [Run] INFO [karma]: Karma v0.12.31 server started at http://localhost:60910/
[04.02.2015 15:35:35.327] [Run] run cancelled

[04.02.2015 15:35:45.826] [Discover] Start (e:\projects\karmvsadapter\karmvsadapter\karma.conf.js)
[04.02.2015 15:35:45.870] [Discover] node node_modules\karma-vs-reporter\karma-vs-reporter discover -o C:\Users\David\AppData\Local\Temp\tmp3082.tmp
[04.02.2015 15:35:46.390] [Discover] Finished (e:\projects\karmvsadapter\karmvsadapter\karma.conf.js)
[04.02.2015 15:35:46.423] [Run] Start (e:\projects\karmvsadapter\karmvsadapter\karma.conf.js)
[04.02.2015 15:35:46.565] [Run] node node_modules\karma-vs-reporter\karma-vs-reporter run -p 61177 -o C:\Users\David\AppData\Local\Temp\tmp32E5.tmp -v C:\Users\David\AppData\Local\Temp\tmp32E6.tmp
[04.02.2015 15:35:47.232] [Run] INFO [Test run]: Start
[04.02.2015 15:35:47.240] [Run] INFO [karma]: Karma v0.12.31 server started at http://localhost:61177/
[04.02.2015 15:41:35.441] [Run] run cancelled
```

Here's my karma.conf:
```
// Karma configuration
// Generated on Wed Jan 28 2015 12:11:32 GMT-0500 (Eastern Standard Time)

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],


    // list of files / patterns to load in the browser
    files: [
      'tests/**/*Test.js'
    ],


    // list of files to exclude
    exclude: [
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
    },


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Chrome', 'PhantomJS'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false
  });
};
```

**Comment by cResults** [comment]
On our production solution none of our tests are displayed in Test Explorer.  All test run as expected when executing karma start karma.conf.src in powershell.

The following files were generated when loading a productions solution:

LOGS (VS Output looked to have the same info):
```
[04.02.2015 16:00:03.992] KarmaTestContainerDiscoverer created
[04.02.2015 16:00:04.988] [Error] Could not read settings
Could not read JSON file e:\projects\sumo\dev\projects\source\web\ui\karma-vs-reporter.json
   at KarmaTestAdapter.KarmaSettings..ctor(String source, IKarmaLogger logger)
Unexpected character encountered while parsing value: ﻿. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target)
   at KarmaTestAdapter.Helpers.Json.PopulateFromFile(String path, Object target)

[04.02.2015 16:00:05.005] Watching 'projects\source\web\ui\karma-vs-reporter.json'
```

karma-vs-reporter.json:

```
﻿{
    "$schema": "http://MortenHoustonLudvigsen.github.io/KarmaTestAdapter/karma-vs-reporter.schema.json",
    "karmaConfigFile": "karma.conf.src.js",
    "ServerMode": true,
    "ServerPort": 3535,
    "LogToFile": true,
    "LogDirectory": "KarmaTestAdapter",
    "OutputDirectory": "KarmaTestAdapter/Output",
    "config": {
        "browsers": [
            "Chrome",
            "PhantomJS"
        ]
    }
}
```

karma.conf.src.js:

```
module.exports = function (config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: './',

    frameworks: ['requirejs', 'jasmine-jquery', 'jasmine', 'jasmine-matchers'],

    // list of files / patterns to load in the browser
    files: [

        'bower_modules/jquery/dist/jquery.js',

        { pattern: 'src/**/*.js', included: false },
        { pattern: 'src/**/*.html', included: false },
        { pattern: 'test/**/*Test.js', included: false }, 
        { pattern: 'lib/Telerik/**/*.js', included: false },

        'src/common/config.js',
        'src/home/home-config.js',

        'test/require.config.js',
        'test/test-main-src.js'
    ],

    // list of files to exclude
    exclude: [
        'src/home/main.js'
    ],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
        '**/require.config.js': ['requireglobal']
    },

    reporters: ['progress'],
    //reporters: ['xml'],

    // web server port
    port: 9876,

    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,

    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,

    browsers: ['Chrome'],

    singleRun: false
  });
};
```

We are using require.js and so our test files are loaded via test-main-src.js:
```
requirejs(['jquery', './../base/src/common/config', './../base/src/home/home-config'], function ($) {
    var tests = [];

    for (var file in window.__karma__.files) {
        if (window.__karma__.files.hasOwnProperty(file)) {
            if (/test\/(home|common|lib)\/.*\.js$/.test(file)) {
                console.log('File: ' + file);
                tests.push(file);
            }
        } 
    }

    var paths = requireCommonConfig.paths, 
        homePaths = requireHomeConfig.paths;

    $.extend(paths, homePaths);

    requirejs.config({
        baseUrl: '/base/src',
        urlArgs: '',
        paths: paths,
        deps: tests,
        callback: window.__karma__.start,
    });
});
```

**Comment by MortenHoustonLudvigsen** [comment]
@cResults Many thanks for the comprehensive info. :smile: 
If there is a `karma-vs-reporter.json` and the adapter fails to load it, no tests will be loaded. This is by design. It seems that that is exactly what is happening in your production solution - at line 0 position 0. It ooccurs to me that the problem might be that your `karma-vs-reporter.json` file has a BOM. The adapter should be more forgiving when loading JSON - I will look into that tomorrow, but in the mean time you could try saving the file as UTF-8 without BOM.

**Comment by cResults** [comment]
Thank you for the rapid response Morten,

I saved the karma-vs-reporter.json as UTF-8 without BOM and the next error is as follows from the log:
```
[04.02.2015 18:47:23.741] KarmaTestContainerDiscoverer created
[04.02.2015 18:47:24.710] [Get config] Start (c:\root\ui\karma-vs-reporter.json)
[04.02.2015 18:47:24.746] [Get config] node node_modules\karma-vs-reporter\karma-vs-reporter get-config -c karma-vs-reporter.json -o KarmaTestAdapter\Output\get-config.20150204T184724\KarmaTestAdapter.config.json
[04.02.2015 18:47:25.049] [Get config] Finished (c:\root\ui\karma-vs-reporter.json)
[04.02.2015 18:47:25.114] [Error] One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at KarmaTestAdapter.Helpers.Sha1Utils.GetHash(String path, String currentHash)
   at KarmaTestAdapter.KarmaTestContainer.<GetFiles>b__3(String f)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at KarmaTestAdapter.KarmaTestContainer.GetFiles()
   at KarmaTestAdapter.KarmaTestContainer..ctor(KarmaTestContainerList containerList, String source, IKarmaLogger logger)
   at KarmaTestAdapter.KarmaTestContainerList.CreateContainer(String source)
   at KarmaTestAdapter.KarmaTestContainerDiscoverer.AddTestContainerIfTestFile(String file)
Access to the path 'c:\root\ui\bower_modules\knockout.js' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at KarmaTestAdapter.Helpers.Sha1Utils.GetHash(String path)
   at KarmaTestAdapter.Helpers.Sha1Utils.<GetHash>d__2.MoveNext()

```

From Visual Studio Output was essentially the same.

**Comment by MortenHoustonLudvigsen** [comment]
@cResults Interesting. For some reason access is denied to `c:\root\ui\bower_modules\knockout.js` when the adapter tries to get a SHA1 hash of the contents. I have changed that, so the adapter ignores any errors while getting a hash, assuming that the file has changes if it can't read it. This is in new version 0.7.4.

**Comment by cResults** [comment]
Good Morning Morten,

I got 0.7.4 and I think were getting closer.  The current error that I'm running up against is that it 
    Error: Cannot find module 'karma/node_modules/di'
which you have referenced
```
node_modules\karma-vs-reporter\src\Commands\Discover.js(30):    var di = require('karma/node_modules/di');
node_modules\karma-vs-reporter\src\Commands\ServedRun.js(57)://    var di = require('karma/node_modules/di');
```

Because the depth of node_modules of some of the packages that we use have file lengths that cause problems for Windows file system, we use the node package flatten-packages which moves all the packages to the top level node_modules folder and removes the package redundancy.

Can you reference the di package directly as require('di')?  In the meantime, I'm going to copy di into karma\node_modules to see if that is the last hurdle.

Thank you for your rapid assistance in getting the Karma Test Adapter running on our system.

**Comment by MortenHoustonLudvigsen** [comment]
Good afternoon @cResults :smile: 

Good catch! I hadn't considered that this could happen. I know exactly the problem for Windows file system (specifically the git provider in VS). That's why i have my projects under `C:\Git`. Flattening the packages seems like a pragmatic solution - even though it might cause problems if two packages rely on different versions of a third package?

Anyway, I have made the change you suggested, and bumped to version 0.8.0. You will have to upgrade `karma-vs-reporter`:
````
npm install karma-vs-reporter
````

Thank you so much for putting in the time to help me fix these issues!

**Comment by cResults** [comment]
Hello Morten,

We've ran into two issues.  I think we found a way past the first, but the second appears to be in C#.

Error Message 1:
```
------ Discover test started ------
[karma] Logging to C:\Users\David\AppData\Local\2PS\KarmaTestAdapter\KarmaTestAdapter.log
[karma] [Discover] Start (c:\root\ui\karma-vs-reporter.json)
[karma] [Discover] node node_modules\karma-vs-reporter\karma-vs-reporter discover -c karma-vs-reporter.json -o KarmaTestAdapter\Output\discover.20150206T113152\KarmaTestAdapter.xml
[karma] [Discover] ERROR [vs]: { [Error: ENOENT, no such file or directory 'c:\root\ui\bower_modules\jquery\src\sizzle\dist\dist\sizzle.min.map']
[karma] [Discover]   errno: 34,
[karma] [Discover]   code: 'ENOENT',
[karma] [Discover]   path: 'c:\\root\\ui\\bower_modules\\jquery\\src\\sizzle\\dist\\dist\\sizzle.min.map',
[karma] [Discover]   syscall: 'open' }
[karma] [Discover] Error: ENOENT, no such file or directory 'c:\root\ui\bower_modules\jquery\src\sizzle\dist\dist\sizzle.min.map'
[karma] [Discover]     at Object.fs.openSync (fs.js:432:18)
[karma] [Discover]     at Object.fs.readFileSync (fs.js:289:15)
[karma] [Discover]     at Object.readFile (c:\root\ui\node_modules\karma-vs-reporter\src\Util.js:53:24)
[karma] [Discover]     at Object.readJsonFile (c:\root\ui\node_modules\karma-vs-reporter\src\Util.js:58:31)
[karma] [Discover]     at c:\root\ui\node_modules\karma-vs-reporter\src\Javascript.js:50:29
[karma] [Discover]     at c:\root\ui\node_modules\karma-vs-reporter\src\Util.js:74:16
[karma] [Discover]     at Object.ifTruthy (c:\root\ui\node_modules\karma-vs-reporter\src\Util.js:68:20)
[karma] [Discover]     at Object.ifMatch (c:\root\ui\node_modules\karma-vs-reporter\src\Util.js:73:20)
[karma] [Discover]     at Program.getSourceMapFromComment (c:\root\ui\node_modules\karma-vs-reporter\src\Javascript.js:49:25)
[karma] [Discover]     at c:\root\ui\node_modules\karma-vs-reporter\src\Javascript.js:60:34
[karma] [Discover] Finished (c:\root\ui\karma-vs-reporter.json)
[karma] [Error] Object reference not set to an instance of an object.
   at KarmaTestAdapter.KarmaTestResults.Test.get_FullyQualifiedName()
   at KarmaTestAdapter.KarmaTestResults.Karma.CreateTestCase(Test test, String source)
   at KarmaTestAdapter.KarmaTestResults.Karma.<>c__DisplayClass1.<GetTestCases>b__0(Test test)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at KarmaTestAdapter.KarmaTestDiscoverer.GetTests(IEnumerable`1 sources, IKarmaLogger logger)

========== Discover test finished: 0 found (0:00:22.0370924) ==========
```

The first error is the double dist\dist folder in the jquery sizzle path.  This will be a problem for at least all who are using the bower package of jquery and useing require.js.  It may be a problem for all jquery users.  Regardless.  Here are two of the ways that we found that can get around this.

First, in jquery/src/sizzle/dist/sizzle.min we changed line 3 from 

```//# sourceMappingURL=dist/sizzle.min.map```

to

```//# sourceMappingURL=sizzle.min.map```


A second means that we found that seemed to work was to karma-vs-reporter src Javascript from:

```javascript
            this.path = options.path;
            this.content = options.content;

            this.ast = Util.Try(function () {
                return esprima.parse(_this.content, { loc: true, range: true, comment: true });
            });
            this.smc = this.getSourceMap();
```
to
```javascript
            this.smc = this.getSourceMap();//moving this here seemed to address the issue on the surface
            this.path = options.path;
            this.content = options.content;

            this.ast = Util.Try(function () {
                return esprima.parse(_this.content, { loc: true, range: true, comment: true });
            });
```

The issue that still remains is
```
[karma] [Get config] Start (c:\\root\ui\karma-vs-reporter.json)
[karma] [Get config] node node_modules\karma-vs-reporter\karma-vs-reporter get-config -c karma-vs-reporter.json -o KarmaTestAdapter\Output\get-config.20150206T112514\KarmaTestAdapter.config.json
[karma] [Get config] Finished (c:\\root\ui\karma-vs-reporter.json)
[karma] Watching 'root\ui\karma-vs-reporter.json'
[karma] Watching 'root\ui\karma.conf.src.js'
[karma] Watching 'root\ui\bower_modules\jquery\dist\**\jquery.js'
[karma] Watching 'root\ui\bower_modules\**\*.js'
[karma] Watching 'root\ui\src\**\*.js'
[karma] Watching 'root\ui\lib\Telerik\**\*.js'
[karma] Watching 'root\ui\bower_modules\**\*.html'
[karma] Watching 'root\ui\src\**\*.html'
[karma] Watching 'root\ui\test\**\*Test.js'
[karma] Watching 'root\ui\src\common\**\config.js'
[karma] Watching 'root\ui\src\home\**\home-config.js'
[karma] Watching 'root\ui\test\**\test-main-src.js'
[karma] [Server] Start (c:\\root\ui\karma-vs-reporter.json)
[karma] [Server] node node_modules\karma-vs-reporter\karma-vs-reporter serve -c karma-vs-reporter.json -p 3535
------ Discover test started ------
[karma] [Server] INFO [karma]: Karma v0.12.31 server started at http://localhost:3535/
[karma] [Server] INFO [launcher]: Starting browser Chrome
[karma] Logging to C:\Users\David\AppData\Local\2PS\KarmaTestAdapter\KarmaTestAdapter.log
[karma] [Discover] Start (c:\\root\ui\karma-vs-reporter.json)
[karma] [Discover] node node_modules\karma-vs-reporter\karma-vs-reporter discover -c karma-vs-reporter.json -o KarmaTestAdapter\Output\discover.20150206T112522\KarmaTestAdapter.xml
[karma] [Server] INFO [Chrome 40.0.2214 (Windows 8.1)]: Connected on socket tYi3mt_78iCMRR5ftazl with id 61003076
[karma] [Discover] Finished (c:\\root\ui\karma-vs-reporter.json)
[karma] [Error] Object reference not set to an instance of an object.
   at KarmaTestAdapter.KarmaTestResults.Test.get_FullyQualifiedName()
   at KarmaTestAdapter.KarmaTestResults.Karma.CreateTestCase(Test test, String source)
   at KarmaTestAdapter.KarmaTestResults.Karma.<>c__DisplayClass1.<GetTestCases>b__0(Test test)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at KarmaTestAdapter.KarmaTestDiscoverer.GetTests(IEnumerable`1 sources, IKarmaLogger logger)

========== Discover test finished: 803 found (0:00:35.7404231) ==========
```

I downloaded the solution from git to see if I could find the issue, but I couldn't find the lib needed to fix these references:
![image](https://cloud.githubusercontent.com/assets/5702582/6083904/66b6dcfe-adfa-11e4-9d73-b456c5628a03.png)

Please let me know if you have any questions.  I'll respond as quickly has I can.

Respectfully,

David C

**Comment by MortenHoustonLudvigsen** [comment]
Hi David

I will try to make a project with query and requirejs from bower, and see if I can reproduce the issue this weekend.

I think I know what the C# problem is, and will look at that as well.

I am developing this project in VS 2013, so if you are interested in opening the solution, you will need to install VS 2013 SDK and restore the NuGet packages used by the adapater.

Thanks! :smile:

**Comment by MortenHoustonLudvigsen** [comment]
Hi David

I have been busy adding tests to the C# side of the adapter, so I haven't looked at using jquery and requirejs from bower yet. However, I think the object reference should be resolved in version 0.8.2. Would you be able to test?

If it doesn't work I would be very interested in seeing the XML output from discovery and test run. They can be found if you add the following to your `karma-vs-reporter.json`:

```JSON
"OutputDirectory": "KarmaTestAdapter/Output"
```

Thanks :smile:

**Comment by cResults** [comment]
Hello Morten,

I updated to 0.8.2.  Below is the output window with the current error.

I looked through discover.20150211T095339\KarmaTestAdapter.xml referenced below.  It would take me a good bit of time to edit out all of our production specific information.  I think that time would be better off spent making you  a project that runs with our configuration using karma, require and jasmine.  I'll try to get you that within the next week.

I did notice one thing in the xml file that may need to be addressed.  It appears to me that any and all jasmine tests that are found within the bower_modules are treated the same as jasmine tests that are found within our source code.

If you follow the use of the tests array in test-main-src.js which is at [the bottom of this post](https://github.com/MortenHoustonLudvigsen/KarmaTestAdapter/issues/6#issuecomment-72949391),  you can see where the tests are discovered and passed into require for loading.  This is our implementation following the [pattern in the karma documentation](http://karma-runner.github.io/0.8/plus/RequireJS.html).

If there is something specific that you need from the xml file to trouble shoot the issue below, please let me know.

```
[karma] [Get config] Start (c:\root\ui\karma-vs-reporter.json)
[karma] [Get config] node node_modules\karma-vs-reporter\karma-vs-reporter get-config -c karma-vs-reporter.json -o KarmaTestAdapter\Output\get-config.20150211T095332\KarmaTestAdapter.config.json
[karma] [Get config] Finished (c:\root\ui\karma-vs-reporter.json)
[karma] Watching 'root\ui\karma-vs-reporter.json'
[karma] Watching 'root\ui\karma.conf.src.js'
[karma] Watching 'root\ui\bower_modules\jquery\dist\**\jquery.js'
[karma] Watching 'root\ui\bower_modules\**\*.js'
[karma] Watching 'root\ui\src\**\*.js'
[karma] Watching 'root\ui\bower_modules\**\*.html'
[karma] Watching 'root\ui\src\**\*.html'
[karma] Watching 'root\ui\test\**\*Test.js'
[karma] Watching 'root\ui\src\common\**\config.js'
[karma] Watching 'root\ui\src\home\**\home-config.js'
[karma] Watching 'root\ui\test\**\test-main-src.js'
[karma] [Server] Start (c:\root\ui\karma-vs-reporter.json)
[karma] [Server] node node_modules\karma-vs-reporter\karma-vs-reporter serve -c karma-vs-reporter.json -p 3535
------ Discover test started ------
[karma] [Server] INFO [karma]: Karma v0.12.31 server started at http://localhost:3535/
[karma] [Server] INFO [launcher]: Starting browser Chrome
[karma] Logging to C:\Users\David\AppData\Local\2PS\KarmaTestAdapter\KarmaTestAdapter.log
[karma] [Server] INFO [Chrome 40.0.2214 (Windows 8.1)]: Connected on socket LYd61AlXvNuy97RnIYHR with id 49817209
[karma] [Discover] Start (c:\root\ui\karma-vs-reporter.json)
[karma] [Discover] node node_modules\karma-vs-reporter\karma-vs-reporter discover -c karma-vs-reporter.json -o KarmaTestAdapter\Output\discover.20150211T095339\KarmaTestAdapter.xml
[karma] [Discover] Finished (c:\root\ui\karma-vs-reporter.json)
[karma] [Error] Name
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.TestObject.PrivateSetPropertyValue(TestProperty property, Object value)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.TestObject.SetPropertyValue[T](TestProperty property, T value)
   at KarmaTestAdapter.TestResults.Karma.CreateTestCase(Test test, String source)
   at KarmaTestAdapter.TestResults.Karma.<>c__DisplayClass1.<GetTestCases>b__0(Test test)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at KarmaTestAdapter.KarmaTestDiscoverer.GetTests(IEnumerable`1 sources, IKarmaLogger logger)

========== Discover test finished: 803 found (0:00:33.8141806) ==========
```

**Comment by MortenHoustonLudvigsen** [comment]
Hi David

Sorry for not getting back sooner. I have just released version 0.8.3 which should ignore any tests that don't have a name (this is a bit of a hack - I know).

I have been doing some thinking about the issues you and others have been experiencing. This has prompted me to rethink the adapter. See issue #9.

I will close this issue for now, because I want to concentrate on issue #9.

**Comment by cResults** [comment]
Hello Morten,

I’m sorry I have been silent so long.  I read your proposal in issue 9.  I often make arrays of values and put the it function inside a forEach, so whatever approach you take need to account for this. This should also account for tests being loaded via require.js. All in all,  I think letting karma determine what the tests are makes sense.

I have a project with our configuration of karma require and jasmine with jquery and jqueryui bower modules.  It runs when karma is launched from the command line, but I have checked to see how it behaves with KarmaTestAdapter, nor have I uploaded it to Git.  Is this something that would have value to you?

I appreciate your work on this product and your contributions to the community.

Respectfully,

David C

**Comment by MortenHoustonLudvigsen** [comment]
Hi David

Thank you for your kind words. I have just made a prerelease of the next version (see #9). Hopefully, it should solve the issues you have been having. I would really appreciate it if you could find the time to put it through its paces! :smile:

**Comment by cResults** [comment]
Hello Morten,

I updated to v 1.0.0.   I changed my karma-vs-reporter.json to:
```
﻿{
    "$schema": "http://MortenHoustonLudvigsen.github.io/KarmaTestAdapter/KarmaTestAdapter.schema.json",
    "karmaConfigFile": "karma.conf.src.js",
    "Disabled": false,
    "LogToFile": true,
    "LogDirectory": "TestResults/Karma",
    "ServerMode": true,
    "ServerPort": 3535,
    "config": {
        "browsers": [ "Chrome"]
    }
}
```

The test explorer starts to discover tests, but never finishes.  Here's the output:
```
[karma] [Projects\Source\Web\ui] Creating KarmaTestContainer for Projects\Source\Web\ui\karma.conf.js
[karma] [Projects\Source\Web\ui] Watching Projects\Source\Web\ui\KarmaTestAdapter.json
[karma] [Projects\Source\Web\ui] KarmaTestContainer created
------ Discover test started ------
[karma] [Projects\Source\Web\ui] [Karma] [karma]: starting karma server
[karma] [Projects\Source\Web\ui] [Karma] [VS Reporter]: Created
[karma] Refreshing containers: Karma started for Projects\Source\Web\ui
[karma] [Projects\Source\Web\ui] [Karma] [VS Server]: Started - port: 52103
========== Discover test finished: 810 found (0:00:06.2483249) ==========
------ Discover test started ------
[karma] [Projects\Source\Web\ui] [Discover] Discovering tests
```

The 810 found are all C# tests.  None of the JavaScript tests show up in the Test Explorer.

It may be worthy to note that the instance of Chrome used by Karma doesn't start.  Let me know if there is any more info I can get for you.

**Comment by cResults** [comment]
I just noticed that ```Projects\Source\Web\ui\KarmaTestAdapter.json``` doesn't exist in the file system. Should it?

**Comment by cResults** [comment]
I renamed karma-vs-reporter.json to KarmaTestAdapter.json and now I get:
```
[karma] [Projects\Source\Web\ui] Creating KarmaTestContainer for Projects\Source\Web\ui\KarmaTestAdapter.json
[karma] [Error] [Projects\Source\Web\ui] Could not read settings
Could not read JSON file e:\Projects\Sumo\Dev\Projects\Source\Web\ui\KarmaTestAdapter.json
   at KarmaTestAdapter.Helpers.Json.PopulateFromFile(String path, Object target) in c:\Git\KarmaTestAdapter\KarmaTestAdapter\Helpers\Json.cs:line 57
   at KarmaTestAdapter.TestAdapter.KarmaSettings..ctor(String configFile, Func`2 fileExists, String baseDirectory, IKarmaLogger logger) in c:\Git\KarmaTestAdapter\KarmaTestAdapter\TestAdapter\KarmaSettings.cs:line 28
Unexpected character encountered while parsing value: ﻿. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target)
   at KarmaTestAdapter.Helpers.Json.PopulateFromFile(String path, Object target) in c:\Git\KarmaTestAdapter\KarmaTestAdapter\Helpers\Json.cs:line 53

[karma] [Projects\Source\Web\ui] Watching Projects\Source\Web\ui\KarmaTestAdapter.json
[karma] [Projects\Source\Web\ui] Watching Projects\Source\Web\ui\KarmaTestAdapter.json
[karma] [Warning] [Projects\Source\Web\ui] Could not read settings: Could not read JSON file e:\Projects\Sumo\Dev\Projects\Source\Web\ui\KarmaTestAdapter.json
------ Discover test started ------
========== Discover test finished: 810 found (0:00:06.2072832) ==========
```

**Comment by MortenHoustonLudvigsen** [comment]
@cResults I have made a few breaking changes:

* The  npm module `karma-vs-reporter` is deprecated and no longer used. You can safely uninstall it

* The optional configuration file is no longer called `karma-vs-reporter.json`. It is now called `KarmaTestAdapter.json`.

See <http://mortenhoustonludvigsen.github.io/KarmaTestAdapter/> for details.

Hope this helps :smile:

**Comment by MortenHoustonLudvigsen** [comment]
@cResults  Please make sure `KarmaTestAdapter.json` is encoded using UTF-8.

**Comment by cResults** [comment]
Notepad++ say that it is UTF-8.  Does it need to be UTF-8 without BOM?

**Comment by MortenHoustonLudvigsen** [comment]
@cResults Probably, though I had that solved in the old version. It must have been missed in the new version. I'll check that later.

**Comment by MortenHoustonLudvigsen** [comment]
@cResults By the way, the settings `ServerMode` and `ServerPort` are deprecated. With the new adapter Karma is always run in the background, and the port is assigned automatically.

**Comment by cResults** [comment]
I changed it to UTF-8 without BOM and rec'd the following error.  I changed it back and still get the same:
```
[karma] [Projects\Source\Web\ui] Creating KarmaTestContainer for Projects\Source\Web\ui\KarmaTestAdapter.json
[karma] [Error] [Projects\Source\Web\ui] Could not read settings
Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at KarmaTestAdapter.Helpers.PathUtils.GetRelativePath(String basePath, String fullPath, Boolean onlyLocal) in c:\Git\KarmaTestAdapter\KarmaTestAdapter\Helpers\PathUtils.cs:line 85
   at KarmaTestAdapter.TestAdapter.KarmaSettings..ctor(String configFile, Func`2 fileExists, String baseDirectory, IKarmaLogger logger) in c:\Git\KarmaTestAdapter\KarmaTestAdapter\TestAdapter\KarmaSettings.cs:line 30

[karma] [Projects\Source\Web\ui] Watching Projects\Source\Web\ui\KarmaTestAdapter.json
[karma] Refreshing containers: KarmaTestContainer created
[karma] [Warning] [Projects\Source\Web\ui] Could not read settings: Invalid URI: The format of the URI could not be determined.

```

**Comment by MortenHoustonLudvigsen** [comment]
@cResults Thank you for your perseverance! I have created two new issues:

* #12 Con not read KarmaTestAdapter.json if it is encoded with a BOM
* #13 The format of the URI could not be determined

I will look at #13 immediately.

**Comment by cResults** [comment]
Thank you Morten. I'm following both of those issues.
